@host=http://localhost:5209
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Mohammad",
    "lastName": "Arfizurrahman",
    "email": "arahman1@gmail.com",
    "password":"Ar123$5!"
}

